---
title: Goal scoring in the AFL
subtitle: A linear modelling exploration
authors:
  - name: Trent Henderson
    affiliation: OLET5608
    email: then6675@uni.sydney.edu.au
abstract: |
  Enter the text of your abstract here.
bibliography: references.bib
biblio-style: unsrt
output: 
  rticles::arxiv_article:
    keep_tex: true
---

# Introduction



# Data set

Historical AFL data has been made readily-accessible in an open-source setting through the R package `fitzRoy`. The package provides a simple API that accesses a range of data sources that collate AFL data. Examples of these sources include:

\begin{itemize}
  \item{AFL}
  \item{AFL Tables}
  \item{Squiggle}
  \item{FootyWire}
\end{itemize}

The data itself is diverse, covering domains as broad as player and match statistics, Brownlow medal votes, betting odds, attendance numbers, and match times. This report focuses on player and match statistics by aggregating quantities of interest to team-per-match-level sums using data for the 2010-2019 seasons, inclusive. This time period is partially arbitrary, but was made on the basis of recency and potential homogeneity. The 2020 season is a strong example of this, where the season length was truncated and played almost entirely in Queensland due to COVID-19 impacts. This means the standard set up of games - having a home and away team - was not normal in 2020 and may represent a heterogenous set.

The variables that were retained for the purposes of this analysis included team-match-level counts of:

\begin{itemize}
  \item{Goals}
  \item{Marks}
  \item{Handballs}
  \item{Hit outs}
  \item{Tackles}
  \item{Rebounds}
  \item{Inside 50s}
  \item{Clearances}
  \item{Clangers}
  \item{Free kicks for}
  \item{Contested possessions}
  \item{Contested marks}
  \item{Marks inside 50}
\end{itemize}

Specifically, this report aims to explore the following research question: *What gameplay attributes are predictors of goals scored by teams in AFL matches?*

# Analysis



# Results



# Discussion


